CREATE DATABASE Cadastro_Cliente;


CREATE TABLE [TABELA DE CLIENTES](
[CPF] [CHAR] (11),
[NOME] [VARCHAR] (100),
[ENDERECO1] [VARCHAR] (150),
[ENDERECO2] [VARCHAR] (150),
[BAIRRO] [VARCHAR] (50),
[CIDADE] [VARCHAR] (50),
[ESTADO] [CHAR] (2),
[CEP] [CHAR] (8),
[DATA DE NASCIMENTO] [DATE],
[IDADE] [SMALLINT],
[SEXO] [CHAR] (1),
[LIMITE DE CREDITO] [MONEY],
[VOLUME DE COMPRA] [FLOAT],
[PRIMEIRA COMPRA] [BIT])


CREATE TABLE [TABELA DE VENDEDORES]
( [MATRICULA] varchar(5),
[NOME] varchar(100),
[PERCENTUAL COMISSÃO] float);


-- INSERIR DADOS

INSERT INTO [TABELA DE CLIENTES] ([NOME], [BAIRRO], [CEP], [CIDADE], [CPF], [DATA DE NASCIMENTO], [ENDERECO1], [ENDERECO2],
[ESTADO], [IDADE], [LIMITE DE CREDITO], [PRIMEIRA COMPRA], [SEXO], [VOLUME DE COMPRA]) VALUES
('SABRINA HELENA', 'SRA LURDES', '33920542', 'BELO HORIZONTE', '089121', '2004-08-01', 'RUA TAL DE FULANO', 'EM FRENTE PADARIA TAL', 
'MG', 18, 500, 1, 'F', 300.2);

INSERT INTO [TABELA DE VENDEDORES]
([MAtRICULA], [NOME], [PERCENTUAL COMISSÃO])
VALUES
('00235','Márcio Almeida Silva',0.08);

INSERT INTO [TABELA DE VENDEDORES]
([MAtRICULA], [NOME], [PERCENTUAL COMISSÃO])
VALUES
('00236','Cláudia Morais',0.08);

INSERT INTO [TABELA DE VENDEDORES] VALUES ('00239', 'Alberto de Sá Verneck', 0.08);

-- UPDATE

UPDATE [TABELA DE CLIENTES] SET [NOME] = 'Helena Ferreira' WHERE [CPF] ='089121'

ALTER TABLE [TABELA DE PRODUTOS] ALTER COLUMN [CODIGO DO PRODUTO] VARCHAR(50) NOT NULL

ALTER TABLE [TABELA DE PRODUTOS] 
ADD CONSTRAINT PK_TABELA_DE_PRODUTOS PRIMARY KEY CLUSTERED ([CODIGO DO PRODUTO])

ALTER TABLE [TABELA DE CLIENTES] ALTER COLUMN [CPF] VARCHAR(11) NOT NULL

ALTER TABLE [TABELA DE CLIENTES]
ADD CONSTRAINT PK_TABELA_DE_CLIENTES PRIMARY KEY CLUSTERED (CPF)

-- DELETE

DELETE [TABELA DE CLIENTES] WHERE [NOME] = 'Helena Ferreira'